config/routes.rb
Rails.application.routes.draw do

  resources :members, only: [:show, :new, :create]

  resources :submissions, only: [:create, :show] do
    resource :involvement, only: [:show, :update], controller: :involvement
    resource :distance, only: [:show, :update], controller: :distance
    resource :activities, only: [:show, :update, :new, :create]
    resource :postcode, only: [:show, :update], controller: :postcode
  end

  resources :recommendations, only: :show
  resources :recommendations_test, only: :show

  namespace :admin do
    root to: redirect('admin/members')
    resources :members, only: [:index, :create, :show]
    resources :archived_members, only: [:index, :show]
    resources :activities, only: [:show]
  end

  resources :pages, only: :show
  root to: 'pages#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :interests
  has_many :submissions, through: :interests
  has_many :members, through: :submissions

  scope :active, -> { where(active: true) }
  scope :with_thumbs_up, -> { joins(:interests).where(interests: {response: 'yes'}).group('activities.id')}
  scope :with_thumbs_down, -> { joins(:interests).where(interests: {response: 'no'}).group('activities.id')}
  scope :with_final_submission, ->{ joins(:submissions).where('submissions.final' => true)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :activity
  belongs_to :submission

  scope :by_position, -> { order('position ASC') }

  scope :thumbs_up, -> { where(response: 'yes') }
  scope :thumbs_down, -> { where(response: 'no') }
  scope :unseen, -> { where(response: 'unseen') }
  scope :with_final_submission, ->{ joins(:submission).where('submissions.final' => true)}

  validates :activity, :submission, :response, :position, presence: true

  def response_emoji
    case response
    when 'yes' then '👍'
    when 'no' then '👎'
    else '🙈'
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  has_many :submissions

  scope :with_final_submission, ->{ joins(:submissions).merge(Submission.final) }

  geocoded_by :geocoding_address
  after_validation :geocode, if: ->(obj){ obj.postcode.present? && obj.postcode_changed? }

  def anonymous?
    source != 'admin'
  end

  def status
    if submissions.finished.any?
      'finished'
    elsif submissions.any?
      'partial'
    else
      'none'
    end
  end

  def geocoding_address
    if postcode.blank?
      nil
    else
      "#{postcode}, UK"
    end
  end

  def to_param
    uuid
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :member
  has_many :interests
  has_many :yes_activities, -> { where("interests.response" => 'yes')}, through: :interests, :source => :activity

  scope :by_created, ->{ order('created_at ASC')}
  scope :finished, ->{ where(finished: true) }
  scope :final, ->{ where(final: true) }

  accepts_nested_attributes_for :interests

  def to_param
    uuid
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :find_submission, :redirect_if_finished

  def show
    activities = Activity.active.to_a.shuffle
    @interests = activities.each_with_index.map do |activity, position|
      @submission.interests.build(activity: activity, position: position, response: 'unseen')
    end
  end

  def update
    if @submission.update(params.require(:submission).permit(interests_attributes: [:activity_id, :position, :response]))
      redirect_to new_submission_activities_path(@submission)
    else
      @interests = @submission.interests
      render :show
    end
  end

  def new
    @required_interests = 5
    @ups = @submission.interests.thumbs_up.count
    @downs = @submission.interests.thumbs_down.count
    @unseens = @submission.interests.unseen.count
  end

  def create
    @submission.update!(activity_suggestion: params[:suggestion], finished: true, final: true)
    redirect_to page_path(:thanks)
  end

end

app/controllers/admin/activities_controller.rb
module Admin
  class ActivitiesController < AdminController

    def show
      @activity = Activity.find(params[:id])
      @interested_members = @activity.members.merge(Interest.thumbs_up).where('submissions.final' => true)
    end
  end
end

app/controllers/admin/archived_members_controller.rb
module Admin
  class ArchivedMembersController < AdminController

    def index
      @members = Member.order('created_at ASC')
    end

  end
end

app/controllers/admin/members_controller.rb
require 'securerandom'

module Admin
  class MembersController < AdminController

    def index
      @members = Member.order('created_at ASC')

      @submissions = Submission.final
      @activities = Activity.active

      @involvement_responses = Submission.final.where.not(involvement: "").pluck(:involvement).uniq
      @activity_suggestions = Submission.final.where.not(activity_suggestion: "").pluck(:activity_suggestion).uniq
      @interests = Activity.joins(interests: :submission).where('interests.response' => 'yes', 'submissions.final' => true).map do |activity|
        [activity, activity.interests.joins(:submission).where('interests.response' => 'yes', 'submissions.final' => true).size]
      end.sort_by(&:last).reverse
      @disinterests = Activity.joins(interests: :submission).where('interests.response' => 'no', 'submissions.final' => true).map do |activity|
        [activity, activity.interests.joins(:submission).where('interests.response' => 'no', 'submissions.final' => true).size]
      end.sort_by(&:last).reverse
    end

    def create
      member = Member.create!(
        postcode: params[:postcode],
        uuid: SecureRandom.hex(3)
      )
      redirect_to admin_members_path, flash: {member_uuid: member.uuid}
    end

    def show
      @member = Member.find_by!(uuid: params[:id])
    end

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: Rails.application.secrets.admin_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :track_source

  private

  def redirect_if_finished
    if @submission.finished?
      redirect_to page_path(:thanks)
    end
  end

  def find_submission
    @submission = Submission.find_by!(uuid: params[:submission_id])
  end

  def track_source
    cookies[:source] = params[:source] if !params[:source].blank?
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def new
    @member = Member.new
  end

  def create
    member = Member.create!(
      name: params[:member][:name],
      uuid: SecureRandom.hex(3),
      source: cookies[:source] || 'anonymous'
    )
    submission = member.submissions.create!(uuid: SecureRandom.hex(3))
    redirect_to submission_activities_path(submission)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    redirect_to new_member_path
  end

  def show
    render params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recommendations_helper.rb
require 'googlestaticmap'

module RecommendationsHelper
  def intro(arguments={}, &blk)
    render 'recommendations/cards/intro', arguments.merge(content: capture(&blk))
  end

  def recommendation(arguments={}, &blk)
    raise 'An ID must be provided for each recommendation so we can track clicks. This should be a short description of this particular recommendation. e.g. getting-fit-roundhay-park' if arguments[:id].blank?
    raise 'A reason must be provided for each recommendation' if arguments[:why].blank?
    arguments[:back_content] ||= 'OK, noted! Your feedback is useful for when I’m finding things for you to do.'
    render 'recommendations/cards/recommendation', arguments.merge(content: capture(&blk))
  end

  def map(latitude:, longitude:, zoom: 14)

    location = MapLocation.new(latitude: latitude, longitude: longitude)
    map = GoogleStaticMap.new(
      width: 500,
      height: 128,
      zoom: zoom,
      center: location,
      api_key: Rails.application.secrets.maps_key
    )
    map.markers << MapMarker.new(location: location)
    render 'recommendations/cards/map', map_url: map.url('https')
  end

  def interest_button(message)
    render 'recommendations/cards/interest_button', message: message
  end

  def want_to_start(arguments={}, &blk)
    render 'recommendations/cards/want_to_start'
  end

end

app/views/activities/new.html.erb
<%= form_tag submission_activities_path(@submission) do |f| %>

  <h1>What factors do you think make something 'cooperative'?</h1>
  <%= text_area_tag :suggestion %>
  <%= submit_tag 'Next', class: 'btn btn-primary' %>
<% end %>

app/views/activities/show.html.erb
<%= form_for @submission, url: submission_activities_path(@submission), method: :put do |f| %>
  <h1>Is this cooperating?</h1>
  <p class="begin-statement">If two neighbours came together to...</p>
  <%= f.fields_for :interests, @interests do |interest_fields| %>
    <fieldset class="thumbs-up-down">
      <%= interest_fields.hidden_field :position %>
      <%= interest_fields.hidden_field :activity_id %>
      <div class="statement statement-color-<%= rand(1..8) %>">
        <p>
          <%= interest_fields.object.activity.name %>
        </p>
      </div>
      <div class="thumbs-up-down-choice">
        <%= interest_fields.label :response_yes, 'Yes!' %>
        <%= interest_fields.radio_button :response, 'yes' %>
        <%= interest_fields.label :response_no, 'No' %>
        <%= interest_fields.radio_button :response, 'no' %>
        <%= interest_fields.radio_button :response, 'unseen' %>
      </div>
    </fieldset>
  <% end %>
<% end %>

app/views/admin/activities/show.html.erb
<%= render 'shared/google_maps' %>

<h1><%=@activity.name %></h1>

<h2>Interested members (<%= @interested_members.count %>)</h2>
<div id="admin-map" style="width: 100%; height: 500px;">
</div>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Created</th>
      <th>Postcode</th>
      <th>Source</th>
      <th>Submissions</th>
    </tr>
  </thead>
  <tbody id="members">
    <% @interested_members.each do |member| %>
      <tr class="member" data-latitude="<%=member.latitude%>" data-longitude="<%=member.longitude%>">
        <td><%= member.uuid %></td>
        <td><%= member.created_at %></td>
        <td class="postcode"><%= member.postcode %></td>
        <td><%= member.source %></td>
        <td class="submissions <%=member.status%>"><%= link_to member.submissions.count, admin_member_path(member) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/archived_members/index.html.erb
<h1>All Members</h1>
<%= render 'admin/members/list', members: @members %>

app/views/distance/show.html.erb
<%= render 'shared/google_maps' %>
<% content_for :head do %>
  <% if Rails.application.secrets.routing_key %>
    <script src="https://releases.route360.net/r360-js/latest.js"></script>
  <% end %>
<% end %>

<h1>How far can you travel?</h1>

<%= form_for @form, as: :submission, url: submission_distance_path(@submission), method: :put do |f| %>

  <%= render 'shared/errors', object: @form, message: 'Please fill in all the details' %>

  <p>
    Find things to do
    <%= f.number_field :distance, min: 1, max: 30, pattern: "[0-9]" %>
    minutes
    <%= f.select :distance_mode, options_for_select(@form.transport_options)%>
    from home.
  </p>
  <% if Rails.application.secrets.maps_key %>
    <div id="member-map" data-postcode="<%=@submission.member.postcode%>" data-route360-key="<%=Rails.application.secrets.routing_key%>" style="width: 100%; height: 400px;">
    </div>
  <% end %>
  <%= f.submit 'Next', class: 'btn btn-primary' %>
<% end %>

app/views/involvement/show.html.erb
<h1>Why do you want to do something in your neighbourhood?</h1>

<%= form_for @form, as: :submission, url: submission_involvement_path(@submission), method: :put do |f| %>

  <%= render 'shared/errors', object: @form, message: 'Please answer this question so we can create personalised suggestions for you' %>

  <%= f.label :involvement, 'This question is optional but we will use this information to better match you to opportunities.' %>
  <%= f.text_area :involvement %>
  <%= f.submit 'Next', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <% if Rails.env.production? && !@disable_analytics %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-105074981-3"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-105074981-3');
      </script>
    <% end %>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Co-op Communities</title>
    <meta name="description" content="">
    <%= csrf_meta_tags %>
    <%#<%= favicon_tag 'images/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>
  <body class="<%= controller.controller_name %> <%= yield (:body_class) %>">
    <div class="app-content">
      <div class="content-wrapper">

        <header class="wrap header-main header-design-manual">
          <a class="coop-logo" aria-label="Homepage" href="#">
            <img src="<%= image_path 'logos/coop-logo.svg' %>" alt="Co-op">
          </a>
        </header>

        <main id="main" class="main">
          <article class="wrap">
              <div class="row margin-bh">
                <div class="column large-7">
                  <%= yield %>
                </div>
              </div>
          </article>
          <footer>
            <div class="wrap">
              <div class="row">
                <div class="column">
                  <p class="copyright">© Co-operative Group Limited. All rights reserved.</p>
                </div>
              </div>
            </div>
          </footer>
        </main>

      </div>
    </div>
  </body>
</html>

app/views/layouts/recommendations.html.erb
<% content_for :body_class, "recommendations-page" %>
<%= render template: 'layouts/application' %>

app/views/members/_copy.html.erb
<h1>What do we mean by co&dash;operation?</h1>

<p>
  We've been talking about <strong>increasing co-operation in communities</strong>, but in our meetings and conversations it becomes clear we have different ideas of what this means.
</p>

<p>
  Have a go at selecting if you think something is co-opearting or not, and let's see where we have agreement or disagreement.
</p>

<%= form_for @member do |f| %>
  <h1>What's your name?</h1>
  <%= f.text_field :name %>
  <%= f.submit 'Get started', class: 'btn btn-primary' %>
<% end %>

app/views/members/new.html.erb
<%= render 'copy', get_started_path: members_path %>

app/views/members/show.html.erb
<%= render 'copy', get_started_path: submissions_path(member_id: @member.uuid) %>

app/views/postcode/show.html.erb
<h1>What's your postcode?</h1>

<%= form_for @form, as: :submission, url: submission_postcode_path(@submission), method: :put do |f| %>

  <%= render 'shared/errors', object: @form, message: 'Please enter a postcode' %>

  <%= f.label :postcode, 'We will use this information to find things near you' %>
  <%= f.text_field :postcode, required: true%>
  <%= f.submit 'Next', class: 'btn btn-primary' %>
<% end %>

app/views/recommendations/3789f7.html.erb
<%= intro my_name: 'Helen', avatar: 'helen.png' do %>
  <p>Hi Jodie, I’ve had a go at finding some things for you to do near LS11. I’m interested to see what you think of my suggestions. If I’ve got something wrong or you want me to find something else then let me know. I hope these ideas help you get more out of your area.</p>
<% end %>

<%= recommendation id: 'beeston-craft-cafe', why: 'You said you’d like to make handmade gifts' do %>
  <h1><span>Could a craft cafe help you make handmade gifts?</span> There’s a craft cafe that takes place in Beeston during term time every Wednesday morning. They share crafts and ideas while relaxing over a cuppa and cake so it might be a good place to try some new crafts and make lovely gifts for people.</h1>
  <section class="recommendation-details">
    <header>
      <dl>
        <dt>Beeston Craft Cafe</dt>
        <dd>Every Wednesday during term time from 10am to 2pm</dd>
        <dd>No cost</dd>
        <dd class="availability">Next session: Wednesday 17 January at 10am</dd>
      </dl>

    </header>
    <div class="location-details">
      <div class="map">
        <%= map(latitude: 53.782096, longitude: -1.547146) %>
      </div>
      <dl>
        <dt>Church Of The Nazarene, Hunslet Hall Rd, Leeds LS11 6TT</dt>
        <dd>37 minutes walk <a target="_blank" href="https://www.google.co.uk/maps/dir//Church+Of+The+Nazarene,+Hunslet+Hall+Road,+Leeds/@53.7721926,-1.5673377,15z/data=!4m9!4m8!1m0!1m5!1m1!1s0x48795c262ad70ec3:0x99598db17ab1985!2m2!1d-1.5481426!2d53.7820225!3e2" target="_blank">Get directions</a></dd>
      </dl>
    </div>
    <section class="call-to-action">
      <div class="action">
        <h2>Find out more or contact them on their </h2>
        <a href="https://www.facebook.com/craftcafebeeston/" target="_blank">Facebook page</a>
      </div>
    </section>
  </section>
<% end %>

<%= recommendation id: 'learn-chinese-with-fan', why: 'You said you’d like to learn a new language and to cook new things' do %>
  <h1><span>Would you like to learn Chinese and how to cook chinese food with Fan?</span> He is a student at the University and will teach you in exchange for helping him with his english.</h1>
  <section class="recommendation-details">
    <header>
      <dl>
        <dt>Fan</dt>
        <dd>Available to meet in Leeds</dd>
      </dl>
    </header>
    <section class="call-to-action">
      <div class="action">
        <h2>Contact Fan on Language Exchange</h2>
        <a href="https://mylanguageexchange.com/MemberInfo.asp?uid=3763492" target="_blank">mylanguageexchange.com</a>
        <dd class="note">(Note: You’ll need to register first)</dd>
      </div>
    </section>
  </section>
<% end %>

<%= recommendation id: 'cottingley-community-orchard', why: 'You said you’d like to make cider' do %>
  <h1><span>How about getting involved with a community orchard so you can make cider in the Autumn?</span> Cider making tends to happen in October and last year there were <a target="_blank" href="https://www.theorchardproject.org.uk/news/leedsappleday2017/" target="_blank">lots of opportunities</a> to get involved in Leeds.  Cottingley Orchards is the closest place to you. They held a fun apple day last year and there’s a tree planting coming up in February organised by Cottingley in Bloom if you want get involved now in preparation for cider season 🍏🍺</h1>
  <section class="recommendation-details">
    <header>
      <dl>
        <dt>Cottingley Community Orchard</dt>
        <dd>No cost</dd>
        <dd class="availability">Next event: 20 February at 10am planting twenty more apple trees in the orchard</dd>
      </dl>

    </header>
    <div class="location-details">
      <div class="map">
        <%= map(latitude: 53.769166, longitude: -1.582092) %>
      </div>
      <dl>
        <dt>Meet at The Heights, Cottingley</dt>
        <dd>20 minutes walk <a target="_blank" href="https://www.google.co.uk/maps/dir//53.769166,-1.582092/@53.7659781,-1.5797918,16z/data=!4m2!4m1!3e2" target="_blank">Get directions</a></dd>
      </dl>
    </div>
    <section class="call-to-action">
      <div class="action">
        <h2>Find out more or contact them on their </h2>
        <a href="https://www.facebook.com/groups/419769031403382/about/" target="_blank">Facebook page</a>
      </div>
    </section>
  </section>
<% end %>

<%= recommendation id: 'leeds-community-energy-coop', why: 'You said you’d like to put up a wind turbine' do %>
  <h1><span>Do you want to join Leeds Community Energy co-operative?</span> They are on a mission to develop community-owned renewable energy generation projects in Leeds to create a fair and clean, sustainable environment for future generations. Would you like to get involved? They meet fortnightly and are currently looking for volunteers.</h1>
  <section class="recommendation-details">
    <header>
      <dl>
        <dt>Leeds Community Energy co-operative</dt>
        <dd>Meet fortnightly</dd>
      </dl>
    </header>
    <section class="call-to-action">
      <div class="action">
        <h2>Contact them via </h2>
        <a href="http://leedscommunityenergy.org.uk/" target="_blank">leedscommunityenergy.org.uk</a>
      </div>
    </section>
  </section>
<% end %>

app/views/recommendations/4b41fa.html.erb
<%= intro my_name: 'James', avatar: 'james-r.png' do %>
  <p>Hi Janet. I’ve had a go at finding some things for you to do near WF3. I’m interested to see what you think of my suggestions. I hope these ideas help you get more out of your area.</p>
<% end %>

<%= recommendation id: 'learn-italian-with-ilva', why: 'You said you’d like to learn Italian' do %>
  <h1><span>Learn Italian with Ilva.</span> She’ll teach you in exchange for helping her with English. Fantastico! 🇮🇹</h1>
  <section class="recommendation-details">
    <header>
      <img src="<%= image_path 'iiva.png' %>" alt="">
      <dl>
        <dt>Ilva</dt>
        <dd>Available to meet in Leeds</dd>
      </dl>
    </header>
    <section class="call-to-action">
      <div class="action">
        <h2>Contact Iiva on Language Exchange</h2>
        <a href="https://mylanguageexchange.com/MemberInfo.asp?uid=3449315" target="_blank">mylanguageexchange.com</a>
      </div>
    </section>
  </section>
<% end %>

<%= recommendation id: 'grow-garden-appltree', why: 'You said you’d like to grow a garden and plant a communal herb garden' do %>
  <h1><span>Grow a garden at Appletree,</span> an outdoor community resource, where people of all ages and from all walks of life get together to grow.</h1>
  <section class="recommendation-details">
    <header>
      <img src="<%= image_path 'appletree.png' %>" alt="">
      <dl>
        <dt>Appletree Allotment and Community Garden</dt>
        <dd class="availability">Next open: Tomorrow 10am - 4pm</dd>
      </dl>
    </header>
    <div class="location-details">
      <div class="map">
        <%= map(latitude: 53.695692, longitude: -1.520273) %>
      </div>
      <dl>
        <dt>Off Agbrigg Road, Wakefild, WF1 5AE (opposite Mr Happy)</dt>
        <dd>Around 12 minute drive <a target="_blank" href="https://www.google.com/maps/dir//41+Agbrigg+Rd,+Wakefield+WF1,+UK/@53.6640623,-1.5520518,12z/data=!4m9!4m8!1m0!1m5!1m1!1s0x4879665d0b6a8c71:0x47c4718207df3c77!2m2!1d-1.4820125!2d53.6640827!3e0?hl=en-GB" target="_blank">Get directions</a></dd>
      </dl>
    </div>
    <section class="call-to-action">
      <div class="action">
        <h2>Find out more</h2>
        <a target="_blank" href="http://www.wakefield.gov.uk/sport-and-leisure/wakefield-wellbeing/appletree" target="_blank">wakefield.gov.uk</a>
      </div>
    </section>
  </section>
<% end %>


<%= recommendation id: 'borrowing-tools-from-others', why: 'You said you’d like to grow a garden' do %>
  <h1><span>Someone nearby wants to grow a garden.</span> You’re not alone!</h1>
  <div class="other-people">
    <img src="<%= image_path 'anonymous.svg' %>" alt=""><br /><br />
  </div>
  <section class="start-something-detail">
    <p>They live about a 15 minute drive from you. Do you want me to introduce you?</p>
    <%= interest_button "Yes, introduce me" %>
    <p class="helper-text">(Only your first name and email address will be shared)</p>
  </section>
<% end %>

<%= recommendation id: 'bonus-suggestion-meet-food-italian', why: 'You said you’d like to meet new people and enjoy food together and learn Italian' do %>
  <h1><span class="bonus">Bonus suggestion:</span> I have found an Italian cooking course where you’ll get chance to meet new people and learn some new dishes.</h1>
  <p class="expanded-intro">
    It’s an extra <span class="info-warning">5 minutes further away than you said you’d be happy to drive</span>, but if you’re into all things Italian then this could be one not to miss!
  </p>
  <section class="recommendation-details">
    <header>
      <div class="date">
        <span>6</span>
        <span>Jun</span>
      </div>
      <dl>
        <dt>Italian Kitchen cooking course</dt>
        <dd class="availab  ility">Start date: Wednesday 6:30pm - 8:30</dd>
        <dd>Cost: £150 for 4 evening classes</dd>
      </dl>
    </header>
    <div class="location-details">
      <%= map(latitude: 53.695692, longitude: -1.520273) %>
      <dl>
        <dt>Gate 3, 43a Springfield Centre, Bagley lane, Farsley, Leeds</dt>
        <dd><span class="info-warning">32 minutes</span> <a target="_blank" href="https://www.google.co.uk/maps/dir//Get+Cooking,+Cookery+School,+43a+Springfield+Commercial+Centre,+Bagley+Lane,+Farsley,+Leeds+LS28+5LY/@53.8171953,-1.7348138,12z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x487be203fb953a11:0x42fe38b083d20ff5!2m2!1d-1.6647745!2d53.8172157!3e0">Get directions</a></dd>
      </dl>
    </div>
    <section class="call-to-action">
      <div class="action">
        <h2>Find out more</h2>
        <a href="https://get-cooking.org.uk/portfolio/italian-kitchen/" target="_blank">get-cooking.org.uk/portfolio/italian-kitchen</a>
      </div>
    </section>
  </section>
<% end %>

<%= recommendation id: 'start-singing-group', why: "You said you'd like to sing", back_content: "Thanks for letting me know, I'll be in touch." do %>
  <h1><span>🎉 Want something a bit more challenging?</span> You said you would like to sing, but I can’t find a group near where you live. Would you like to start one?</h1>
  <section class="recommendation-details">
    <%= want_to_start %>
  </section>
  <p class="expanded-intro">I can see if I can find other people in your neighbourhood who also wants to sing.</p>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="form-error">
    <%= message %>
  </div>
<% end %>

app/views/shared/_google_maps.html.erb
<% content_for :head do %>
  <% if Rails.application.secrets.maps_key %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.secrets.maps_key%>" type="text/javascript"></script>
  <% end %>
<% end %>